# opencv kütüphanesini içe aktaralım
# ...

# numpy kütüphanesini içe aktaralım
# ...

# resmi siyah beyaz olarak içe aktaralım resmi çizdirelim
# ...

# resim üzerinde bulunan kenarları tespit edelim ve görselleştirelim edge detection
# ...

# yüz tespiti için gerekli haar cascade'i içe aktaralım
# ...

# yüz tespiti yapıp sonuçları görselleştirelim
# ...

# HOG ilklendirelim insan tespiti algoritmamızı çağıralım ve svm'i set edelim
# ...

# resme insan tespiti algoritmamızı uygulayalım ve görselleştirelim
# ...
